name: Run Tests Daily

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests with Gradle
      run: ./gradlew test

    - name: Set up Allure
      run: |
        npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: |
        allure generate --clean
        allure serve
